### ISSUE TITLE
Error in sampled_softmax_loss after converting code to tf 1.0+

### ISSUE THREAD

**Issue by bwang482** [rafaljozefowicz/lm#3]
Hi Rafal, thank you for the code! Not sure if you are still supporting it.

But I keep getting errors using it with tf 1.2, after converting your code to be compatible with the new version tf using tf_upgrade.py. At first it complained `targets` has int32 and doesn't match float32 in 

```
            loss = tf.nn.sampled_softmax_loss(softmax_w, softmax_b, tf.to_float(inputs),
                                              targets, hps.num_sampled, hps.vocab_size)
```

So I changed `targets` to `tf.to_float(targets)`; now I am getting the error shown below:

```
$ python single_lm_train.py --logdir log --num_gpus 1 --datadir data --hpconfig emb_size=100,state_size=256,projected_size=128
Traceback (most recent call last):
  File "single_lm_train.py", line 38, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "single_lm_train.py", line 27, in main
    run_train(dataset, hps, FLAGS.logdir + "/train", ps_device="/gpu:0")
  File "/home/ccrmad/Code/lm-master/run_utils.py", line 14, in run_train
    model = LM(hps, "train", ps_device)
  File "/home/ccrmad/Code/lm-master/language_model.py", line 24, in __init__
    loss = self._forward(i, xs[i], ys[i], ws[i])
  File "/home/ccrmad/Code/lm-master/language_model.py", line 100, in _forward
    tf.to_float(targets), hps.num_sampled, hps.vocab_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 1247, in sampled_softmax_loss
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_impl.py", line 1007, in _compute_sampled_logits
    inputs, sampled_w, transpose_b=True) + sampled_b
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/math_ops.py", line 1825, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 1242, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2536, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1818, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1768, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 595, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 659, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 1 and 128 for 'model/model/sampled_softmax_loss/MatMul_1' (op: 'MatMul') with input shapes: [5120,1], [?,128].
```
Any idea why?

**Comment by northanapon** [comment]
@bluemonk482, I am not a developer on this, but [tf.nn.sampled_softmax_loss api](https://www.tensorflow.org/api_docs/python/tf/nn/sampled_softmax_loss) has changed. Specifically, you need to call it by:

```python
# assuming that inputs is the outputs from RNNCell (or any hidden states)
loss = tf.nn.sampled_softmax_loss(
    softmax_w, softmax_b, targets, inputs, hps.num_sampled, hps.vocab_size)
```

**Comment by bwang482** [comment]
So I only needed to switch `targets` with `inputs`, and it is working now! Brilliant, thanks @NorThanapon !!
